name: ephemeral

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:  
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Clone repo
      uses: actions/checkout@v2
    - name: Clone ephemeral-cluster repo
      uses: actions/checkout@v2
      with:
        repository: celestiaorg/ephemeral-cluster
        path: ephemeral
        ref: jbowen93/evmos
    - name: "Setup and Test Cluster"
      run: |
        cd ephemeral
        ./debug-start-cluster.sh
